project_id = "wirxvaxlqdbivfhovrnc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://wirxvaxlqdbivfhovrnc.supabase.co"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[functions.sync-campaign-data]
verify_jwt = false

[functions.sync-ga-accounts]
verify_jwt = false

[functions."oauth/google_analytics/start"]
verify_jwt = false

[functions."oauth/google_analytics/callback"]
verify_jwt = false

[functions."oauth/google_ads/start"]
verify_jwt = false

[functions."oauth/meta_ads/start"]
verify_jwt = false

[db]
port = 54322